---

- name: copy keys to publication directory
  copy:
    remote_src: yes
    src: "{{ ca_openssl_path }}/subject_keys/{{ item.name }}.pem"
    dest: "{{ ca_publication_location }}/{{ item.name }}.pem"
  loop: "{{ openvpn_clients }}"

- name: copy config files to publication directory
  copy:
    remote_src: yes
    src: "{{ openvpn_config_directory }}/{{ item.name }}.ovpn"
    dest: "{{ ca_publication_location }}/{{ item.name }}.ovpn"
  loop: "{{ openvpn_clients }}"

- name: create tarballs
  archive:
    path:
      - "{{ ca_publication_location }}/{{ item.name }}.pem"
      - "{{ ca_publication_location }}/{{ item.name }}.crt"
      - "{{ ca_publication_location }}/{{ item.name }}.ovpn"
    dest: "{{ ca_publication_location }}/{{ item.name }}.tgz"
  loop: "{{ openvpn_clients }}"

- name: fetch tarballs
  fetch:
    src: "{{ ca_publication_location }}/{{ item.name }}.tgz"
    dest: "{{ openvpn_fetch_client_config_to }}"
  loop: "{{ openvpn_clients }}"
